import { useEffect, useState } from "react";
import { Page, PageBody, PageHeader } from "@/components/Page";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { api, type EntitySummary } from "../api.js";
import { Markdown } from "../components/Markdown.js";

export function DigestView({ embedded = false }: { embedded?: boolean }) {
  const [digest, setDigest] = useState<{ date: string; content: string } | null>(null);
  const [entities, setEntities] = useState<EntitySummary[]>([]);
  const [missing, setMissing] = useState(false);
  const [running, setRunning] = useState(false);

  // the digest opens with its own H1; the view header already says it
  const body = digest ? digest.content.replace(/^#\s.*\n/, "").trim() : null;

  const load = () =>
    api
      .getLatestDigest()
      .then((d) => {
        setDigest(d);
        setMissing(false);
      })
      .catch(() => setMissing(true));

  useEffect(() => {
    load();
    api
      .listEntities()
      .then((r) => setEntities(r.entities))
      .catch(() => {});
  }, []);

  const consolidate = async () => {
    setRunning(true);
    try {
      await api.runConsolidation();
      // consolidation runs in the background; poll for a fresh digest
      const poll = setInterval(() => {
        load();
      }, 3000);
      setTimeout(() => {
        clearInterval(poll);
        setRunning(false);
      }, 60000);
    } catch {
      setRunning(false);
    }
  };

  const description = digest
    ? `Morning briefing for ${digest.date}.`
    : "A two-minute briefing on what changed.";
  const action = (
    <Button
      variant="outline"
      onClick={() => void consolidate()}
      disabled={running}
      className="border-line bg-transparent text-faded hover:border-lamp-dim hover:bg-transparent hover:text-paper"
    >
      {running ? "Consolidating…" : "Run consolidation"}
    </Button>
  );
  const article = (
    <article className={cn("pb-16", embedded ? "mt-6" : "mt-8")}>
      {body ? (
        <Markdown text={body} entities={entities} />
      ) : missing ? (
        <p className="text-sm text-faded">
          No digest yet. It is generated by the nightly consolidation — or run one now with the
          button above.
        </p>
      ) : null}
    </article>
  );

  if (embedded) {
    return (
      <>
        <div className="flex items-center justify-between gap-4">
          <p className="text-sm text-muted-foreground">{description}</p>
          {action}
        </div>
        {article}
      </>
    );
  }
  return (
    <Page>
      <PageHeader title="Daily digest" description={description} actions={action} />
      <PageBody>{article}</PageBody>
    </Page>
  );
}
