import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { api, type EntitySummary } from "../api.js";
import { Markdown } from "../components/Markdown.js";

export function DigestView() {
  const [digest, setDigest] = useState<{ date: string; content: string } | null>(null);
  const [entities, setEntities] = useState<EntitySummary[]>([]);
  const [missing, setMissing] = useState(false);
  const [running, setRunning] = useState(false);

  const load = () =>
    api
      .getLatestDigest()
      .then((d) => {
        setDigest(d);
        setMissing(false);
      })
      .catch(() => setMissing(true));

  useEffect(() => {
    load();
    api.listEntities().then((r) => setEntities(r.entities)).catch(() => {});
  }, []);

  const consolidate = async () => {
    setRunning(true);
    try {
      await api.runConsolidation();
      // consolidation runs in the background; poll for a fresh digest
      const poll = setInterval(() => {
        load();
      }, 3000);
      setTimeout(() => {
        clearInterval(poll);
        setRunning(false);
      }, 60000);
    } catch {
      setRunning(false);
    }
  };

  return (
    <div className="h-full overflow-y-auto">
      <div className="mx-auto max-w-2xl px-8 py-10">
        <header className="rise flex items-baseline justify-between">
          <div>
            <h2 className="font-serif text-3xl text-paper">Daily digest</h2>
            <p className="mt-1 text-sm text-dim">
              {digest ? `Morning briefing for ${digest.date}.` : "A two-minute briefing on what changed."}
            </p>
          </div>
          <Button
            variant="outline"
            onClick={() => void consolidate()}
            disabled={running}
            className="border-line bg-transparent text-faded hover:border-lamp-dim hover:bg-transparent hover:text-paper"
          >
            {running ? "Consolidating…" : "Run consolidation"}
          </Button>
        </header>

        <article className="rise rise-1 mt-8 pb-16">
          {digest ? (
            <Markdown text={digest.content} entities={entities} />
          ) : missing ? (
            <p className="text-sm text-faded">
              No digest yet. It is generated by the nightly consolidation — or run one now with the button above.
            </p>
          ) : null}
        </article>
      </div>
    </div>
  );
}
