import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { getCodingAgent } from "../src/coding-agent/index.js";
import { openDatabase, type MeosDatabase } from "../src/db/database.js";
import { KnowledgeStore } from "../src/knowledge/store.js";
import { CodingAgentLlmClient } from "../src/llm/coding-agent-client.js";
import { StubLlmClient } from "../src/llm/stub.js";
import { runConsolidation } from "../src/memory/consolidate.js";
import { WikiWriter } from "../src/wiki/writer.js";
import { failingFallback } from "./fixtures/index.js";

/**
 * LIVE (#native-agent-intelligence) — the nightly digest generated by a REAL
 * local coding-agent CLI (`CodingAgentLlmClient` over Claude Code), proving the
 * plain-text `complete` path works as native intelligence.
 *
 * Gated behind `MEOS_LIVE_AGENT=1` (needs the `claude` CLI installed + logged in):
 *   MEOS_LIVE_AGENT=1 pnpm --filter @meos/core exec vitest run test/live-agent-digest.test.ts
 *
 * The fallback THROWS, so a pass means the agent itself produced the digest text
 * (a non-image `complete` never delegates to the fallback unless the run fails).
 * Embedder omitted + regenerateWiki:false so the digest is the ONLY agent call.
 */
const RUN = process.env.MEOS_LIVE_AGENT === "1";

describe.runIf(RUN)("live: nightly digest via a real coding agent", () => {
  it("writes a non-trivial markdown digest through the agent (no fallback)", async () => {
    const db: MeosDatabase = openDatabase(":memory:");
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "meos-live-digest-"));
    try {
      const store = new KnowledgeStore(db);
      // Give the digest something concrete to report.
      const dana = store.createEntity({ type: "person", name: "Dana" });
      store.insertObservation({
        entityId: dana.id,
        text: "Dana shipped the Orion launch this week.",
        confidence: 0.8,
      });

      const agent = new CodingAgentLlmClient({
        agent: getCodingAgent("claude"),
        scratchDir: path.join(tmpDir, "scratch"),
        fallback: failingFallback(),
      });
      // The wiki writer is required but never invoked (regenerateWiki:false).
      const wiki = new WikiWriter(store, new StubLlmClient(), path.join(tmpDir, "wiki"));

      const report = await runConsolidation({
        store,
        llm: agent,
        wiki,
        digestDir: path.join(tmpDir, "digests"),
        regenerateWiki: false,
      });

      const digest = store.latestDigest()!;

      console.log("[live-agent] digest:\n", digest.content);

      // The agent produced a real digest: persisted, non-trivial, and mirrored to disk.
      expect(digest.content.trim().length).toBeGreaterThan(20);
      const onDisk = fs.readFileSync(
        path.join(tmpDir, "digests", `${report.digestDate}.md`),
        "utf-8",
      );
      expect(onDisk).toBe(digest.content);
    } finally {
      db.close();
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  }, 240_000);
});
